version: "3.5"
services:
  event_generator:
    container_name: bothelp_demo_event_generator
    image: bothelp_demo_app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: ./bin/app generate-events
    depends_on:
      - redis
    cap_add:
      - SYS_TIME
    tty: true
  worker:
    image: bothelp_demo_app
    volumes:
      - ./logs:/opt/app/logs
    command: ./bin/app run-worker
    depends_on:
      - redis
    cap_add:
      - SYS_TIME
    tty: true
  redis:
    container_name: bothelp_demo_redis
    ports:
      - "6500:6379"
    expose:
      - 6379
    image: redis:alpine
